/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const CreateCourseArgs = IDL.Record({
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
});
export const CourseId = IDL.Nat;
export const LessonId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
  'lessonOrder' : IDL.Vec(LessonId),
});
export const CreateLessonArgs = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
  'courseId' : CourseId,
  'orderIndex' : IDL.Nat,
});
export const QuizId = IDL.Nat;
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
  'quizId' : IDL.Opt(QuizId),
  'courseId' : CourseId,
  'orderIndex' : IDL.Nat,
});
export const Question = IDL.Record({
  'explanation' : IDL.Text,
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const CreateQuizArgs = IDL.Record({
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const QuizScoreEntry = IDL.Record({
  'lessonId' : LessonId,
  'score' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const StudentProgress = IDL.Record({
  'quizScores' : IDL.Vec(QuizScoreEntry),
  'userId' : UserId,
  'completedLessons' : IDL.Vec(LessonId),
  'enrolledAt' : Timestamp,
  'courseId' : CourseId,
  'lastVisitedLessonId' : IDL.Opt(LessonId),
});
export const UpdateCourseArgs = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
});
export const UpdateLessonArgs = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
  'quizId' : IDL.Opt(QuizId),
  'courseId' : CourseId,
  'orderIndex' : IDL.Nat,
});
export const UpdateQuizArgs = IDL.Record({
  'id' : QuizId,
  'lessonId' : LessonId,
  'title' : IDL.Text,
  'questions' : IDL.Vec(Question),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([CreateCourseArgs], [Course], []),
  'createLesson' : IDL.Func([CreateLessonArgs], [Lesson], []),
  'createQuiz' : IDL.Func([CreateQuizArgs], [Quiz], []),
  'deleteCourse' : IDL.Func([CourseId], [IDL.Bool], []),
  'deleteLesson' : IDL.Func([LessonId], [IDL.Bool], []),
  'deleteQuiz' : IDL.Func([QuizId], [IDL.Bool], []),
  'enrollInCourse' : IDL.Func([CourseId], [StudentProgress], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
  'getLessonsForCourse' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'getMyProgress' : IDL.Func([CourseId], [IDL.Opt(StudentProgress)], ['query']),
  'getQuizForLesson' : IDL.Func([LessonId], [IDL.Opt(Quiz)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
  'saveQuizScore' : IDL.Func([CourseId, LessonId, IDL.Nat], [], []),
  'updateCourse' : IDL.Func([UpdateCourseArgs], [IDL.Opt(Course)], []),
  'updateLesson' : IDL.Func([UpdateLessonArgs], [IDL.Opt(Lesson)], []),
  'updateQuiz' : IDL.Func([UpdateQuizArgs], [IDL.Opt(Quiz)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const CreateCourseArgs = IDL.Record({
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
  });
  const CourseId = IDL.Nat;
  const LessonId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
    'lessonOrder' : IDL.Vec(LessonId),
  });
  const CreateLessonArgs = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
    'courseId' : CourseId,
    'orderIndex' : IDL.Nat,
  });
  const QuizId = IDL.Nat;
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
    'quizId' : IDL.Opt(QuizId),
    'courseId' : CourseId,
    'orderIndex' : IDL.Nat,
  });
  const Question = IDL.Record({
    'explanation' : IDL.Text,
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const CreateQuizArgs = IDL.Record({
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const QuizScoreEntry = IDL.Record({
    'lessonId' : LessonId,
    'score' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const StudentProgress = IDL.Record({
    'quizScores' : IDL.Vec(QuizScoreEntry),
    'userId' : UserId,
    'completedLessons' : IDL.Vec(LessonId),
    'enrolledAt' : Timestamp,
    'courseId' : CourseId,
    'lastVisitedLessonId' : IDL.Opt(LessonId),
  });
  const UpdateCourseArgs = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
  });
  const UpdateLessonArgs = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
    'quizId' : IDL.Opt(QuizId),
    'courseId' : CourseId,
    'orderIndex' : IDL.Nat,
  });
  const UpdateQuizArgs = IDL.Record({
    'id' : QuizId,
    'lessonId' : LessonId,
    'title' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([CreateCourseArgs], [Course], []),
    'createLesson' : IDL.Func([CreateLessonArgs], [Lesson], []),
    'createQuiz' : IDL.Func([CreateQuizArgs], [Quiz], []),
    'deleteCourse' : IDL.Func([CourseId], [IDL.Bool], []),
    'deleteLesson' : IDL.Func([LessonId], [IDL.Bool], []),
    'deleteQuiz' : IDL.Func([QuizId], [IDL.Bool], []),
    'enrollInCourse' : IDL.Func([CourseId], [StudentProgress], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
    'getLessonsForCourse' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'getMyProgress' : IDL.Func(
        [CourseId],
        [IDL.Opt(StudentProgress)],
        ['query'],
      ),
    'getQuizForLesson' : IDL.Func([LessonId], [IDL.Opt(Quiz)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
    'saveQuizScore' : IDL.Func([CourseId, LessonId, IDL.Nat], [], []),
    'updateCourse' : IDL.Func([UpdateCourseArgs], [IDL.Opt(Course)], []),
    'updateLesson' : IDL.Func([UpdateLessonArgs], [IDL.Opt(Lesson)], []),
    'updateQuiz' : IDL.Func([UpdateQuizArgs], [IDL.Opt(Quiz)], []),
  });
};

export const init = ({ IDL }) => { return []; };