/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'title' : string,
  'thumbnail' : string,
  'difficulty' : Difficulty,
  'description' : string,
  'learningObjectives' : Array<string>,
  'lessonOrder' : Array<LessonId>,
}
export type CourseId = bigint;
export interface CreateCourseArgs {
  'title' : string,
  'thumbnail' : string,
  'difficulty' : Difficulty,
  'description' : string,
  'learningObjectives' : Array<string>,
}
export interface CreateLessonArgs {
  'title' : string,
  'content' : string,
  'learningObjectives' : Array<string>,
  'courseId' : CourseId,
  'orderIndex' : bigint,
}
export interface CreateQuizArgs {
  'lessonId' : LessonId,
  'title' : string,
  'questions' : Array<Question>,
}
export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'learningObjectives' : Array<string>,
  'quizId' : [] | [QuizId],
  'courseId' : CourseId,
  'orderIndex' : bigint,
}
export type LessonId = bigint;
export interface Question {
  'explanation' : string,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export interface Quiz {
  'id' : QuizId,
  'lessonId' : LessonId,
  'title' : string,
  'questions' : Array<Question>,
}
export type QuizId = bigint;
export interface QuizScoreEntry { 'lessonId' : LessonId, 'score' : bigint }
export interface StudentProgress {
  'quizScores' : Array<QuizScoreEntry>,
  'userId' : UserId,
  'completedLessons' : Array<LessonId>,
  'enrolledAt' : Timestamp,
  'courseId' : CourseId,
  'lastVisitedLessonId' : [] | [LessonId],
}
export type Timestamp = bigint;
export interface UpdateCourseArgs {
  'id' : CourseId,
  'title' : string,
  'thumbnail' : string,
  'difficulty' : Difficulty,
  'description' : string,
  'learningObjectives' : Array<string>,
}
export interface UpdateLessonArgs {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'learningObjectives' : Array<string>,
  'quizId' : [] | [QuizId],
  'courseId' : CourseId,
  'orderIndex' : bigint,
}
export interface UpdateQuizArgs {
  'id' : QuizId,
  'lessonId' : LessonId,
  'title' : string,
  'questions' : Array<Question>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[CreateCourseArgs], Course>,
  'createLesson' : ActorMethod<[CreateLessonArgs], Lesson>,
  'createQuiz' : ActorMethod<[CreateQuizArgs], Quiz>,
  'deleteCourse' : ActorMethod<[CourseId], boolean>,
  'deleteLesson' : ActorMethod<[LessonId], boolean>,
  'deleteQuiz' : ActorMethod<[QuizId], boolean>,
  'enrollInCourse' : ActorMethod<[CourseId], StudentProgress>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getLesson' : ActorMethod<[LessonId], [] | [Lesson]>,
  'getLessonsForCourse' : ActorMethod<[CourseId], Array<Lesson>>,
  'getMyProgress' : ActorMethod<[CourseId], [] | [StudentProgress]>,
  'getQuizForLesson' : ActorMethod<[LessonId], [] | [Quiz]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'markLessonComplete' : ActorMethod<[CourseId, LessonId], undefined>,
  'saveQuizScore' : ActorMethod<[CourseId, LessonId, bigint], undefined>,
  'updateCourse' : ActorMethod<[UpdateCourseArgs], [] | [Course]>,
  'updateLesson' : ActorMethod<[UpdateLessonArgs], [] | [Lesson]>,
  'updateQuiz' : ActorMethod<[UpdateQuizArgs], [] | [Quiz]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];