/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateLessonArgs {
    title: string;
    content: string;
    learningObjectives: Array<string>;
    courseId: CourseId;
    orderIndex: bigint;
}
export type Timestamp = bigint;
export interface UpdateQuizArgs {
    id: QuizId;
    lessonId: LessonId;
    title: string;
    questions: Array<Question>;
}
export type LessonId = bigint;
export interface Quiz {
    id: QuizId;
    lessonId: LessonId;
    title: string;
    questions: Array<Question>;
}
export interface CreateQuizArgs {
    lessonId: LessonId;
    title: string;
    questions: Array<Question>;
}
export interface Course {
    id: CourseId;
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
    lessonOrder: Array<LessonId>;
}
export type UserId = Principal;
export interface UpdateLessonArgs {
    id: LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId?: QuizId;
    courseId: CourseId;
    orderIndex: bigint;
}
export interface Lesson {
    id: LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId?: QuizId;
    courseId: CourseId;
    orderIndex: bigint;
}
export interface CreateCourseArgs {
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
}
export interface StudentProgress {
    quizScores: Array<QuizScoreEntry>;
    userId: UserId;
    completedLessons: Array<LessonId>;
    enrolledAt: Timestamp;
    courseId: CourseId;
    lastVisitedLessonId?: LessonId;
}
export type CourseId = bigint;
export interface UpdateCourseArgs {
    id: CourseId;
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
}
export interface Question {
    explanation: string;
    questionText: string;
    correctAnswerIndex: bigint;
    options: Array<string>;
}
export interface QuizScoreEntry {
    lessonId: LessonId;
    score: bigint;
}
export type QuizId = bigint;
export enum Difficulty {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(args: CreateCourseArgs): Promise<Course>;
    createLesson(args: CreateLessonArgs): Promise<Lesson>;
    createQuiz(args: CreateQuizArgs): Promise<Quiz>;
    deleteCourse(id: CourseId): Promise<boolean>;
    deleteLesson(id: LessonId): Promise<boolean>;
    deleteQuiz(id: QuizId): Promise<boolean>;
    enrollInCourse(courseId: CourseId): Promise<StudentProgress>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(id: CourseId): Promise<Course | null>;
    getLesson(id: LessonId): Promise<Lesson | null>;
    getLessonsForCourse(courseId: CourseId): Promise<Array<Lesson>>;
    getMyProgress(courseId: CourseId): Promise<StudentProgress | null>;
    getQuizForLesson(lessonId: LessonId): Promise<Quiz | null>;
    isCallerAdmin(): Promise<boolean>;
    listCourses(): Promise<Array<Course>>;
    markLessonComplete(courseId: CourseId, lessonId: LessonId): Promise<void>;
    saveQuizScore(courseId: CourseId, lessonId: LessonId, score: bigint): Promise<void>;
    updateCourse(args: UpdateCourseArgs): Promise<Course | null>;
    updateLesson(args: UpdateLessonArgs): Promise<Lesson | null>;
    updateQuiz(args: UpdateQuizArgs): Promise<Quiz | null>;
}
import type { Course as _Course, CourseId as _CourseId, CreateCourseArgs as _CreateCourseArgs, Difficulty as _Difficulty, Lesson as _Lesson, LessonId as _LessonId, Quiz as _Quiz, QuizId as _QuizId, QuizScoreEntry as _QuizScoreEntry, StudentProgress as _StudentProgress, Timestamp as _Timestamp, UpdateCourseArgs as _UpdateCourseArgs, UpdateLessonArgs as _UpdateLessonArgs, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: CreateCourseArgs): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(to_candid_CreateCourseArgs_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Course_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(to_candid_CreateCourseArgs_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Course_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLesson(arg0: CreateLessonArgs): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0);
                return from_candid_Lesson_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0);
            return from_candid_Lesson_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuiz(arg0: CreateQuizArgs): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: CourseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: LessonId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteQuiz(arg0: QuizId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return result;
        }
    }
    async enrollInCourse(arg0: CourseId): Promise<StudentProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return from_candid_StudentProgress_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return from_candid_StudentProgress_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: CourseId): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: LessonId): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonsForCourse(arg0: CourseId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsForCourse(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsForCourse(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(arg0: CourseId): Promise<StudentProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizForLesson(arg0: LessonId): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizForLesson(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizForLesson(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async markLessonComplete(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async saveQuizScore(arg0: CourseId, arg1: LessonId, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizScore(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCourse(arg0: UpdateCourseArgs): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(to_candid_UpdateCourseArgs_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(to_candid_UpdateCourseArgs_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLesson(arg0: UpdateLessonArgs): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(to_candid_UpdateLessonArgs_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(to_candid_UpdateLessonArgs_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuiz(arg0: UpdateQuizArgs): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Course_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProgress_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProgress): StudentProgress {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizId]): QuizId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonId]): LessonId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Lesson | null {
    return value.length === 0 ? null : from_candid_Lesson_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProgress]): StudentProgress | null {
    return value.length === 0 ? null : from_candid_StudentProgress_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId: [] | [_QuizId];
    courseId: _CourseId;
    orderIndex: bigint;
}): {
    id: LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId?: QuizId;
    courseId: CourseId;
    orderIndex: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        learningObjectives: value.learningObjectives,
        quizId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.quizId)),
        courseId: value.courseId,
        orderIndex: value.orderIndex
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quizScores: Array<_QuizScoreEntry>;
    userId: _UserId;
    completedLessons: Array<_LessonId>;
    enrolledAt: _Timestamp;
    courseId: _CourseId;
    lastVisitedLessonId: [] | [_LessonId];
}): {
    quizScores: Array<QuizScoreEntry>;
    userId: UserId;
    completedLessons: Array<LessonId>;
    enrolledAt: Timestamp;
    courseId: CourseId;
    lastVisitedLessonId?: LessonId;
} {
    return {
        quizScores: value.quizScores,
        userId: value.userId,
        completedLessons: value.completedLessons,
        enrolledAt: value.enrolledAt,
        courseId: value.courseId,
        lastVisitedLessonId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastVisitedLessonId))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CourseId;
    title: string;
    thumbnail: string;
    difficulty: _Difficulty;
    description: string;
    learningObjectives: Array<string>;
    lessonOrder: Array<_LessonId>;
}): {
    id: CourseId;
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
    lessonOrder: Array<LessonId>;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail,
        difficulty: from_candid_Difficulty_n9(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        learningObjectives: value.learningObjectives,
        lessonOrder: value.lessonOrder
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): Difficulty {
    return "Beginner" in value ? Difficulty.Beginner : "Advanced" in value ? Difficulty.Advanced : "Intermediate" in value ? Difficulty.Intermediate : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CreateCourseArgs_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCourseArgs): _CreateCourseArgs {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCourseArgs_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCourseArgs): _UpdateCourseArgs {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateLessonArgs_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateLessonArgs): _UpdateLessonArgs {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: CourseId;
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
}): {
    id: _CourseId;
    title: string;
    thumbnail: string;
    difficulty: _Difficulty;
    description: string;
    learningObjectives: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail,
        difficulty: to_candid_Difficulty_n5(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        learningObjectives: value.learningObjectives
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId?: QuizId;
    courseId: CourseId;
    orderIndex: bigint;
}): {
    id: _LessonId;
    title: string;
    content: string;
    learningObjectives: Array<string>;
    quizId: [] | [_QuizId];
    courseId: _CourseId;
    orderIndex: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        learningObjectives: value.learningObjectives,
        quizId: value.quizId ? candid_some(value.quizId) : candid_none(),
        courseId: value.courseId,
        orderIndex: value.orderIndex
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnail: string;
    difficulty: Difficulty;
    description: string;
    learningObjectives: Array<string>;
}): {
    title: string;
    thumbnail: string;
    difficulty: _Difficulty;
    description: string;
    learningObjectives: Array<string>;
} {
    return {
        title: value.title,
        thumbnail: value.thumbnail,
        difficulty: to_candid_Difficulty_n5(_uploadFile, _downloadFile, value.difficulty),
        description: value.description,
        learningObjectives: value.learningObjectives
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
} {
    return value == Difficulty.Beginner ? {
        Beginner: null
    } : value == Difficulty.Advanced ? {
        Advanced: null
    } : value == Difficulty.Intermediate ? {
        Intermediate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
